import = [
  "~/dotfiles/alacritty/.config/alacritty/catppuccin-mocha.toml"
]

live_config_reload = true

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[font]
size = 20

[window]
padding.x = 10
padding.y = 10
opacity = 0.8
blur = true
decorations = "Buttonless"

[env]
TERM = "xterm-256color"
