import = [
 "~/dotfiles/alacritty/.config/alacritty/base16-alacritty/colors/base16-default-dark-256"
]

live_config_reload = true

[mouse]

[font]
size = 20

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[window]
padding.x = 10
padding.y = 10
opacity = 0.8
blur = true
decorations = "Buttonless"

[env]
TERM = "xterm-256color"
