import = [
  "~/dotfiles/alacritty/.config/alacritty/catppuccin-mocha.toml"
]

live_config_reload = true

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[font]
size = 20



[env]
TERM = "xterm-256color"
