# Reference: https://github.com/i3/i3/blob/next/etc/config

enable-normalization-flatten-containers = false
enable-normalization-opposite-orientation-for-nested-containers = false
accordion-padding = 0
start-at-login = true
after-login-command = [

]
after-startup-command = [
  # JankyBorders has a built-in detection of already running process,
  # so it won't be run twice on AeroSpace restart
  'exec-and-forget /opt/homebrew/opt/borders/bin/borders active_color=0xffe1e3e4 inactive_color=0xff494d64 width=5.0'
]

[[on-window-detected]]
if.app-id = 'com.google.Chrome'
# if.app-name-regex-substring = ''
# if.window-title-regex-substring = ''
run = ['layout tiling', 'move-node-to-workspace 1']  # The callback itself

[[on-window-detected]]
# if.app-id = 'com.jetbrains.intelliJ'
if.app-name-regex-substring = 'intelliJ'
# if.window-title-regex-substring = 'IDEA'
run = ['layout tiling', 'move-node-to-workspace 2']  # The callback itself
 
[[on-window-detected]]
if.app-id = 'org.alacritty'
# if.app-name-regex-substring = ''
# if.window-title-regex-substring = ''
run = ['layout tiling', 'move-node-to-workspace 3']  # The callback itself

[[on-window-detected]]
if.app-id = 'com.tinyspeck.slackmacgap'
# if.app-name-regex-substring = ''
# if.window-title-regex-substring = ''
run = ['layout tiling', 'move-node-to-workspace 4']  # The callback itself

[[on-window-detected]]
if.app-id = 'com.microsoft.Outlook'
# if.app-name-regex-substring = ''
# if.window-title-regex-substring = ''
run = ['layout tiling', 'move-node-to-workspace 4']  # The callback itself

[[on-window-detected]]
if.app-id = 'com.microsoft.Outlook'
# if.app-name-regex-substring = ''
# if.window-title-regex-substring = ''
run = ['layout tiling', 'move-node-to-workspace 4']  # The callback itself

[[on-window-detected]]
if.app-id = 'com.spotify.client'
# if.app-name-regex-substring = ''
# if.window-title-regex-substring = ''
run = ['layout tiling', 'move-node-to-workspace 6']  # The callback itself

[[on-window-detected]]
# if.app-id = 'com.microsoft.teams'
if.app-name-regex-substring = 'teams'
# if.window-title-regex-substring = ''
run = ['layout tiling', 'move-node-to-workspace 6']  # The callback itself

[mode.main.binding]
# alt-enter = 'exec-and-forget open -n /System/Applications/Utilities/Terminal.app'

alt-h = 'focus left'
alt-j = 'focus down'
alt-k = 'focus up'
alt-l = 'focus right'

alt-shift-h = 'move left'
alt-shift-j = 'move down'
alt-shift-k = 'move up'
alt-shift-l = 'move right'

# alt-h = 'split horizontal'
alt-v = 'split vertical'

alt-f = 'fullscreen'

alt-s = 'layout v_accordion' # 'layout stacking' in i3
alt-w = 'layout h_accordion' # 'layout tabbed' in i3
alt-e = 'layout tiles horizontal vertical' # 'layout toggle split' in i3

alt-shift-space = 'layout floating tiling' # 'floating toggle' in i3

# Not supported, because this command is redundant in AeroSpace mental model.
# See: https://nikitabobko.github.io/AeroSpace/guide.html#floating-windows
#alt-space = 'focus toggle_tiling_floating'

# `focus parent`/`focus child` are not yet supported, and it's not clear whether they
# should be supported at all https://github.com/nikitabobko/AeroSpace/issues/5
# alt-a = 'focus parent'



alt-1 = 'workspace 1'
alt-2 = 'workspace 2'
alt-3 = 'workspace 3'
alt-4 = 'workspace 4'
alt-5 = 'workspace 5'
alt-6 = 'workspace 6'
# alt-7 = 'workspace 7'
# alt-8 = 'workspace 8'
# alt-9 = 'workspace 9'
alt-0 = 'workspace 10'


alt-shift-1 = 'move-node-to-workspace 1'
alt-shift-2 = 'move-node-to-workspace 2'
alt-shift-3 = 'move-node-to-workspace 3'
alt-shift-4 = 'move-node-to-workspace 4'
alt-shift-5 = 'move-node-to-workspace 5'
alt-shift-6 = 'move-node-to-workspace 6'
# alt-shift-7 = 'move-node-to-workspace 7'
# alt-shift-8 = 'move-node-to-workspace 8'
# alt-shift-9 = 'move-node-to-workspace 9'
alt-shift-0 = 'move-node-to-workspace 10'

alt-shift-r = 'reload-config'

alt-r = 'mode resize'

[mode.resize.binding]
h = 'resize width -50'
j = 'resize height +50'
k = 'resize height -50'
l = 'resize width +50'
enter = 'mode main'
esc = 'mode main'



